// Original training corpus for the in-browser trigram model.
// ~258 short, simple sentences written for this project — no copied text.
// Punctuation is spaced so the tokenizer treats . , ? ! as their own tokens.
export const CORPUS = [
  // --- animals ---
  "the cat sat on the mat .",
  "the cat sat on the warm floor .",
  "the old cat slept on the mat .",
  "a small cat slept in the sun .",
  "the dog ran across the green field .",
  "the dog barked at the mail truck .",
  "my dog loves long walks in the park .",
  "the bird sang from the tall tree .",
  "a little bird landed on the fence .",
  "the fish swam slowly in the clear water .",
  "the horse ate grass near the old barn .",
  "the cow stood quietly in the field .",
  "a rabbit hopped over the low wall .",
  "the cat chased the red ball .",
  "the dog chased the cat around the house .",
  "the cat drank milk from a small bowl .",
  "the kitten played with a ball of wool .",
  "the old dog slept by the fire .",
  "the cat sat on the chair and watched the rain .",
  "birds fly south when the winter comes .",
  "the duck swam across the quiet pond .",
  "a fox crossed the road at night .",
  "the sheep stayed close to the gate .",
  "the cat jumped onto the kitchen table .",
  "the dog waited by the front door .",
  "the mouse hid under the wooden floor .",
  "bees buzzed around the summer flowers .",
  "the owl watched the field from a high branch .",
  "my cat hates the sound of thunder .",
  "the puppy fell asleep in the basket .",
  "the goat climbed onto the rocks .",
  "ants marched across the warm stone .",
  "the cat sat on the window ledge .",
  "a big dog slept in the shade .",
  "the parrot repeated every word we said .",
  "the cat licked its paw and yawned .",
  // --- weather ---
  "the weather is nice today .",
  "the weather is cold this morning .",
  "i think the weather will change soon .",
  "i think the weather is getting warmer .",
  "the rain fell softly on the roof .",
  "heavy rain flooded the narrow street .",
  "the sun rose over the quiet hills .",
  "the sun set behind the tall buildings .",
  "a cold wind blew through the trees .",
  "the storm passed before midnight .",
  "snow covered the whole town by morning .",
  "the sky turned grey before the storm .",
  "the clouds moved slowly across the sky .",
  "fog covered the bridge at dawn .",
  "it rained all day on sunday .",
  "the morning air felt fresh and cool .",
  "thunder rolled across the dark sky .",
  "the summer heat made everyone slow .",
  "a rainbow appeared after the rain .",
  "the wind pushed the small boat to shore .",
  "winter came early this year .",
  "spring brought new leaves to the trees .",
  "the afternoon sun warmed the old bench .",
  "ice covered the pond in january .",
  "the forecast said rain for the weekend .",
  "we watched the storm from the window .",
  "the weather in the mountains changes fast .",
  "a warm breeze came in from the sea .",
  "the first snow fell while we slept .",
  "the weather report was wrong again .",
  // --- food ---
  "we ate warm bread with butter .",
  "the soup smelled like home .",
  "she baked a chocolate cake for the party .",
  "i like tea with a little honey .",
  "he drinks coffee every morning .",
  "the market sells fresh fruit and vegetables .",
  "we bought apples from the farm stand .",
  "dinner was rice with beans and corn .",
  "the pizza arrived hot and late .",
  "lunch is the best part of my day .",
  "she cut the tomatoes for the salad .",
  "the bread was still warm from the oven .",
  "we shared a bowl of noodles .",
  "the kitchen smelled of onions and garlic .",
  "he made pancakes on saturday morning .",
  "the mango was sweet and ripe .",
  "i had eggs and toast for breakfast .",
  "the tea went cold while we talked .",
  "grandma made soup that could fix a bad day .",
  "we picked berries by the river .",
  "the cheese melted over the warm bread .",
  "salt makes the soup taste better .",
  "the children ate ice cream in the park .",
  "he burned the rice again .",
  "a good meal needs time and care .",
  // --- cities and travel ---
  "the city wakes up before the sun .",
  "the streets were full of people and noise .",
  "the old town has narrow stone streets .",
  "we took the last train home .",
  "the bus was late again this morning .",
  "lights from the tall buildings filled the night .",
  "the bridge crosses the wide river .",
  "we walked along the harbor at sunset .",
  "the market square was busy on friday .",
  "taxis lined up outside the station .",
  "the museum was quiet on monday .",
  "she moved to a new city for work .",
  "the map led us to a small cafe .",
  "traffic filled every road at five .",
  "the train passed fields and small towns .",
  "we got lost in the old quarter .",
  "street music echoed between the walls .",
  "the park in the center is always green .",
  "every city has its own sound .",
  "the airport was crowded before the holiday .",
  "we watched boats come into the port .",
  "the tower is the oldest building in town .",
  "rain makes the city lights look soft .",
  "the last bus leaves at midnight .",
  "a new bakery opened on our street .",
  // --- school and learning ---
  "the teacher wrote the answer on the board .",
  "the students asked many good questions .",
  "i study best in the early morning .",
  "the library is quiet and warm .",
  "she read three books last week .",
  "the test was harder than we expected .",
  "he practices the piano every evening .",
  "the class planted a small garden .",
  "we learned about the stars in science class .",
  "the bell rang and the hall filled with noise .",
  "her notebook is full of small drawings .",
  "the exam starts at nine on monday .",
  "good questions matter more than fast answers .",
  "the school bus stops at the corner .",
  "we solved the puzzle together .",
  "the little kids drew pictures of their pets .",
  "history class told us about old cities .",
  "the homework took the whole evening .",
  "she teaches math with games and stories .",
  "reading opens doors to other worlds .",
  "the professor spoke slowly and clearly .",
  "we watched a film about the ocean .",
  "his favorite subject is geography .",
  "the chalk squeaked on the old board .",
  "learning a language takes time and patience .",
  // --- everyday life ---
  "she opened the window to let in the air .",
  "the house was quiet after the guests left .",
  "he fixed the broken chair with glue .",
  "we played cards until late at night .",
  "the garden needs water every evening .",
  "my keys were in my coat pocket all along .",
  "the phone rang twice and then stopped .",
  "she hums old songs while she cooks .",
  "the clock on the wall runs five minutes fast .",
  "we painted the fence bright blue .",
  "the baby laughed at the funny sound .",
  "he walks to work when the sun is out .",
  "the mirror in the hall is very old .",
  "she planted roses along the path .",
  "the letter arrived two weeks late .",
  "we cleaned the whole house on sunday .",
  "the candle burned low while we talked .",
  "his shoes were wet from the rain .",
  "the neighbors are kind and quiet .",
  "she saves a little money every month .",
  "the door creaks when the wind blows .",
  "we watched the stars from the roof .",
  "the old radio still works fine .",
  "he tells the same joke every year .",
  "the family ate dinner together every night .",
  "her smile made the long day easier .",
  "the children built a fort from old boxes .",
  "i lost my umbrella on the bus .",
  "the children left their wet shoes on the mat .",
  "we planted a tree for the new year .",
  "sleep comes easy after a day outside .",
  "the market opens early on saturday .",
  "she wrote a letter to her old friend .",
  "the small lamp made the room feel warm .",
  "laughter filled the kitchen that evening .",
  "he whistles while he waters the plants .",
  "the stairs creak on the third step .",
  "we folded the clean clothes together .",
  "a quiet morning is a small gift .",
  "the calendar still shows last month .",
  // --- nature ---
  "the river runs slow in late summer .",
  "tall trees line the mountain road .",
  "the lake was still as glass at dawn .",
  "waves crashed against the grey rocks .",
  "the forest smells of rain and earth .",
  "flowers bloom first on the south hill .",
  "the moon lit the path through the field .",
  "stars filled the sky far from the city .",
  "the valley turns gold in october .",
  "a stream cuts through the green meadow .",
  "the desert is cold at night .",
  "leaves fell all week in the yard .",
  "the sea looks different every day .",
  "mountains hold snow into late spring .",
  "the trail ends at a small waterfall .",
  "moss grows on the north side of the trees .",
  "the island has one road and one shop .",
  "the cave stayed cool all summer .",
  "wild horses live on the open plain .",
  "the garden hums with life in june .",
  // --- questions, exclamations, commas ---
  "where did you put the keys ?",
  "what time does the train leave ?",
  "can you hear the rain ?",
  "why is the sky blue ?",
  "do you want tea or coffee ?",
  "how far is the station from here ?",
  "what a beautiful morning !",
  "watch out for the ice !",
  "that was the best meal ever !",
  "well , that was a long day .",
  "yes , the store is open today .",
  "no , the bus does not stop here .",
  "first we eat , then we talk .",
  "the house , like the garden , was small and neat .",
  "slow down , the road is wet .",
  // --- computers, internet, artificial intelligence ---
  "the internet is a network of computers .",
  "the internet is a network that never sleeps .",
  "the internet is a big library that never closes .",
  "the internet is a noisy place .",
  "the internet connects people across the world .",
  "computers follow instructions very quickly .",
  "a computer stores data as numbers .",
  "the computer restarted after the update .",
  "my laptop battery dies before lunch .",
  "the new phone has a better camera .",
  "she writes code for a small company .",
  "the program crashed twice this morning .",
  "software needs testing before release .",
  "the website loads faster now .",
  "we sent the photos over the internet .",
  "the email arrived in the wrong folder .",
  "passwords should be long and strange .",
  "the printer never works when you need it .",
  "artificial intelligence learns patterns from data .",
  "artificial intelligence is changing how we work .",
  "the model predicts the next word from context .",
  "language models learn from huge amounts of text .",
  "a neural network is made of simple parts .",
  "the machine learned to spot cats in photos .",
  "training a model takes a lot of data .",
  "the algorithm sorts the list in seconds .",
  "robots build cars in the big factory .",
  "the chatbot answered my question politely .",
  "smart speakers listen for a wake word .",
  "the screen went dark during the storm .",
  "video calls make far friends feel near .",
  "the game runs smoothly on the old machine .",
  "we backed up the files to the cloud .",
  "the search engine found the answer fast .",
  "data moves through wires and through air .",
  "the keyboard clicks in the quiet office .",
  "every app wants my attention .",
  "the update fixed one bug and added two .",
  "the camera saves each picture to the card .",
  "wifi at the cafe is slow but free .",
  "technology changes , but people stay the same .",
];
